### ISSUE TITLE
graddle for building

### ISSUE THREAD

**Issue by dgu123** [igagis/nitki#4]
Hello , 

how are you ? 
i am still looking your excellent lib, and i am wondering if you would considere graddle as a build for your lib?

kind regard
david

**Comment by igagis** [comment]
Hi,

as Android moved to graddle, I consider moving to graddle too. I'm currently researching how to make AAR packages and how to package native libs. This does not go fast. If you have any patches, feel free to submit pull request.

**Comment by dgu123** [comment]
yes sir !
